

name: Primeiro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  validacao:
    # Maquina Virtual
    runs-on: ubuntu-latest

    # tarefas para essa tarefa 
    steps:
      - name: Fazendo o gitclone
         uses: actions/checkout@v4

    
      - name: Listando o diretorio
        run: ls -l
        
        - name: Deixando uma mensagem
           run: echo "Esta funcionando o CI"
      
